name: flutter_firebase_test
description: Flutter Firebase test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:

  sdk: ">=2.17.1 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  firebase_crashlytics: ^2.8.1
  firebase_remote_config: ^2.0.8

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
